version: '3.1'
services:     
  containertest:
    container_name: dockerserverweb
    image: testimage
    ports:
    - "6969:80"
  sql:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "yourStrong(!)Password" 
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
  lucid:
    container_name: lucidcontainer
    image: httpd
    ports:
    - "2020:80"
  
   